version: '3.7'
services:
    influx-ingester-dummy-mqtt:
        build: 
            context: .
            args:
                config_file: './influx-ingester-dummy-mqtt-config-for-compose.yaml'
        container_name: influx-ingester-dummy-mqtt
        # depends_on:
        #     - mqtt
        # network_mode: host
        networks:
            - dummy-network

    # mqtt:
    #     image: eclipse-mosquitto
    #     container_name: mosquitto
    #     expose:
    #         - "1883"
    #     ports:
    #         - "1883:1883"
    #     # network_mode: host
    #     networks:
    #         - default

networks:
    dummy-network:
