version: '3.7'
services:
    influx-ingester-dummy-mqtt:
        build: 
            context: .
            args:
                config_file: './influx-ingester-dummy-mqtt-config-for-compose.yaml'
        container_name: influx-ingester-dummy-mqtt
        # network_mode: host
        networks:
            - default

networks:
    default:
