version: '3.7'
services:
    influx-ingester-mqtt:
        build: 
            context: .
            args:
                config_file: './mqtt-docker-compose-config.yaml'
        container_name: influx-ingester-mqtt
        # depends_on:
        #     - mqtt
        # network_mode: host
        networks:
            - default

    # mqtt:
    #     image: eclipse-mosquitto
    #     container_name: mosquitto
    #     expose:
    #         - "1883"
    #     ports:
    #         - "1883:1883"
    #     # network_mode: host
    #     networks:
    #         - default

networks:
    default:
